import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { catalogoApi } from '../../api/catalogo';
import type { Producto } from '../../types/models';
import { Modal } from '../../components/Modal';
import { LoadingError } from '../../components/LoadingError';

const empty = { nombre:'', descripcion:'', precio:1, activo:true, categoria_ids:[] as number[], ingrediente_ids:[] as number[] };
export function ProductosPage(){
 const qc=useQueryClient(); const [open,setOpen]=useState(false); const [edit,setEdit]=useState<Producto|null>(null); const [form,setForm]=useState(empty);
 const productos=useQuery({queryKey:['productos'],queryFn:catalogoApi.productos}); const categorias=useQuery({queryKey:['categorias'],queryFn:catalogoApi.categorias}); const ingredientes=useQuery({queryKey:['ingredientes'],queryFn:catalogoApi.ingredientes});
 const save=useMutation({mutationFn:()=> edit ? catalogoApi.editarProducto(edit.id,form) : catalogoApi.crearProducto(form), onSuccess:()=>{qc.invalidateQueries({queryKey:['productos']}); setOpen(false); setEdit(null); setForm(empty)}});
 const del=useMutation({mutationFn:catalogoApi.borrarProducto,onSuccess:()=>qc.invalidateQueries({queryKey:['productos']})});
 function toggle(id:number, field:'categoria_ids'|'ingrediente_ids'){const set=new Set(form[field]); set.has(id)?set.delete(id):set.add(id); setForm({...form,[field]:Array.from(set)});}
 function start(p?:Producto){setEdit(p??null); setForm(p?{nombre:p.nombre,descripcion:p.descripcion??'',precio:p.precio,activo:p.activo,categoria_ids:p.categorias.map(c=>c.id),ingrediente_ids:p.ingredientes.map(i=>i.id)}:empty); setOpen(true)}
 return <section><div className="flex justify-between mb-4"><h2 className="text-2xl font-bold">Productos</h2><button onClick={()=>start()} className="bg-slate-900 text-white px-4 py-2 rounded-xl">Nuevo producto</button></div><LoadingError isLoading={productos.isLoading} error={productos.error as Error|null}/><div className="grid md:grid-cols-2 gap-4">{productos.data?.map(p=><article key={p.id} className="bg-white rounded-2xl shadow p-4"><div className="flex justify-between"><h3 className="font-bold text-lg">{p.nombre}</h3><span className="font-semibold">${p.precio}</span></div><p className="text-sm text-slate-600">{p.descripcion}</p><p className="mt-2 text-sm"><b>Categorías:</b> {p.categorias.map(c=>c.nombre).join(', ') || 'Sin categorías'}</p><p className="text-sm"><b>Ingredientes:</b> {p.ingredientes.map(i=>i.nombre).join(', ') || 'Sin ingredientes'}</p><div className="mt-4 flex gap-2"><Link to={`/productos/${p.id}`} className="px-3 py-1 rounded-lg bg-slate-100">Detalle</Link><button onClick={()=>start(p)} className="px-3 py-1 bg-blue-100 rounded-lg">Editar</button><button onClick={()=>del.mutate(p.id)} className="px-3 py-1 bg-red-100 rounded-lg">Eliminar</button></div></article>)}</div><Modal title={edit?'Editar producto':'Nuevo producto'} open={open} onClose={()=>setOpen(false)}><form onSubmit={(e)=>{e.preventDefault();save.mutate()}} className="grid gap-3"><input className="border rounded-xl p-2" placeholder="Nombre" minLength={3} value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})}/><textarea className="border rounded-xl p-2" placeholder="Descripción" value={form.descripcion} onChange={e=>setForm({...form,descripcion:e.target.value})}/><input className="border rounded-xl p-2" type="number" min="0.01" step="0.01" value={form.precio} onChange={e=>setForm({...form,precio:Number(e.target.value)})}/><div><b>Categorías</b><div className="grid grid-cols-2 gap-1 mt-1">{categorias.data?.map(c=><label key={c.id} className="text-sm"><input type="checkbox" checked={form.categoria_ids.includes(c.id)} onChange={()=>toggle(c.id,'categoria_ids')}/> {c.nombre}</label>)}</div></div><div><b>Ingredientes</b><div className="grid grid-cols-2 gap-1 mt-1">{ingredientes.data?.map(i=><label key={i.id} className="text-sm"><input type="checkbox" checked={form.ingrediente_ids.includes(i.id)} onChange={()=>toggle(i.id,'ingrediente_ids')}/> {i.nombre}</label>)}</div></div><label className="flex gap-2"><input type="checkbox" checked={form.activo} onChange={e=>setForm({...form,activo:e.target.checked})}/> Activo</label><button className="bg-slate-900 text-white rounded-xl p-2">Guardar</button>{save.error && <p className="text-red-600">{save.error.message}</p>}</form></Modal></section>
}
